Contact View
cmachado92/abax-vaadin-starter pull request #2
Opened 2023-09-26 22:14 UTC by ecarballea

It was created Contact Form and List views with sort and filter abilities.

2023-09-27 17:37 UTC, cmachado92 requested changes
Minor things, I will test out the interface later, minor code fixes and questions. All looks good.

2023-09-27 17:37 UTC, cmachado92 commented on src/main/java/com/abax/starter/data/service/ContactService.java
> +
you can probably delete these 2, seems like a bad copy/paste from sample CRM service

2023-09-27 17:37 UTC, cmachado92 commented on src/main/java/com/abax/starter/ui/components/detailsdrawer/DetailsDrawerHeader.java
> +		this.close.setVisible(false);
What was the problem before the addition of these 2 lines?

2023-09-27 17:37 UTC, cmachado92 commented on src/main/java/com/abax/starter/ui/components/navigation/bar/AppBar.java
> +//import com.abax.starter.ui.view.verySimpleEdit.Contacts;
delete, do not comment out

2023-09-27 17:37 UTC, cmachado92 commented on src/main/java/com/abax/starter/ui/components/navigation/bar/AppBar.java
> +//	public void addActionItemClickListener(ComponentEventListener<ClickEvent<Button>> listener) {
delete, don't comment out

2023-09-27 17:37 UTC, cmachado92 commented on src/main/java/com/abax/starter/ui/components/navigation/bar/AppBar.java
> +	public Button addActionItem(VaadinIcon icon, String text, ComponentEventListener<ClickEvent<Button>> listener) {
Please explain a little more about this addition

2023-09-27 17:37 UTC, cmachado92 commented on src/main/java/com/abax/starter/ui/components/navigation/bar/TabBar.java
> +//import com.abax.starter.ui.view.verySimpleEdit.Contacts;
delete

2023-09-27 17:37 UTC, cmachado92 commented on src/main/java/com/abax/starter/ui/components/navigation/tab/NaviTabs.java
> +//import com.abax.starter.ui.view.verySimpleEdit.Contacts;
delete

2023-09-27 17:37 UTC, cmachado92 commented on src/main/java/com/abax/starter/ui/layouts/MainLayout.java
> +//import com.abax.starter.ui.view.verySimpleEdit.Contacts;
delete

2023-09-27 17:37 UTC, cmachado92 commented on src/main/java/com/abax/starter/ui/view/verySimpleEdit/Contacts.java
> +//package com.abax.starter.ui.view.verySimpleEdit;
Just delete Contacts.java

2023-09-27 17:37 UTC, cmachado92 commented on src/main/java/com/abax/starter/ui/view/ContactsView.java
> +//        grid.addSelectionListener(event -> event.getFirstSelectedItem().ifPresent(this::editContact));
delete

2023-09-27 17:37 UTC, cmachado92 commented on src/main/java/com/abax/starter/ui/view/ContactsView.java
> +//        grid.setDataProvider(dataProvider);
delete

2023-09-27 17:37 UTC, cmachado92 commented on src/main/java/com/abax/starter/ui/view/CustomersView.java
> +//							BadgeColor.NORMAL);
delete

2023-09-28 00:57 UTC, ecarballea commented on src/main/java/com/abax/starter/data/service/ContactService.java
> +
I use the customerRepository in the findAllCustomers method (line 28) and I use this method in ContactsView (line 74)

2023-09-28 01:05 UTC, ecarballea commented on src/main/java/com/abax/starter/data/service/ContactService.java
> +
statusRepository will be deleted

2023-09-28 01:10 UTC, ecarballea commented on src/main/java/com/abax/starter/ui/components/detailsdrawer/DetailsDrawerHeader.java
> +		this.close.setVisible(false);
With these 2 lines we can control when the close icon will be showed. For example, in the contactForm I don't want that the close Icon is showed, so if I don't add a listener to the close button, it will be not showed in the Contact Form

2023-09-28 01:33 UTC, ecarballea commented
Thank you so much. I cant reply in the comments one question, so, i put it inside of the question order. 
Here my comments just in case:
" When we have many buttons in the header (ex: add Contact and send email) we want to create each button and assigned their listener, so I created this way to get it.  Any suggestion to enhance, please tell me."

2023-09-28 14:08 UTC, cmachado92 approved these changes
All good

2023-09-29 18:42 UTC, closed without merging