Created Worker Module
cmachado92/abax-vaadin-starter pull request #6
Opened 2023-11-14 20:01 UTC by greycasas

2023-11-15 11:46 UTC, cmachado92 commented on src/main/java/com/abax/starter/data/entity/enums/ContactStatus.java
> +import lombok.Getter;
This line was added, no use, remove

2023-11-15 11:47 UTC, cmachado92 commented on src/main/java/com/abax/starter/data/entity/enums/WorkerStatus.java
> +
remove empty line, this is ultra minor stuff, I know, just pointing out

2023-11-15 11:48 UTC, cmachado92 commented on src/main/java/com/abax/starter/data/entity/AbstractBasicEntity.java
> +
this empty line number 38 was added, remove. After finishing a commit you can check the differences in git

2023-11-15 11:51 UTC, cmachado92 commented on src/main/java/com/abax/starter/data/entity/enums/WorkerStatus.java
> +    INACTIVE("Inactive","Workers that no longer require our services", VaadinIcon.MINUS_CIRCLE, BadgeColor.ERROR);
Workers are actually the employees of the company using the software, so it should say:Workers no longer providing their services.

2023-11-15 11:52 UTC, cmachado92 commented on src/main/java/com/abax/starter/data/entity/Worker.java
> +    private String image = "";
would be awesome if we rename to imagePath, no need to do manually, you can refactor and the IDE will replace name everywhere you use it for you

2023-11-15 11:55 UTC, cmachado92 commented on src/main/java/com/abax/starter/data/repository/LocationRepository.java
>  }
lines 21 and 22 were added and are empty. Line number 4 imports HelloWorld which I assume was for learning, please remove

2023-11-15 11:55 UTC, cmachado92 commented on src/main/java/com/abax/starter/data/service/ContactService.java
> +    public List<Contact> findTest(String firstName,String lastName){
Not a fan of this name, findTest? should be similar to the repository method

2023-11-15 11:56 UTC, cmachado92 commented on src/main/java/com/abax/starter/data/service/ContactService.java
> +    public List<Contact> findTest(String firstName,String lastName){
If this was a test, remove, otherwise rename

2023-11-15 11:57 UTC, cmachado92 commented on src/main/java/com/abax/starter/data/service/WorkerService.java
> +    static final int CACHE_TIME = 30; //seconds
we can increase the cache of worker to 300 seconds (5 mins) since they rarely change that often

2023-11-15 11:59 UTC, cmachado92 commented on src/main/java/com/abax/starter/ui/components/StatusComboBox.java
> +                Notification.show(errorMessage, 3000, Notification.Position.BOTTOM_CENTER);
We have our own implementation for this, UIUtils.showNotification() you can even pass the type in this case error and it would color it red

2023-11-15 11:59 UTC, cmachado92 commented on src/main/java/com/abax/starter/ui/components/StatusComboBox.java
> +import com.vaadin.flow.component.notification.Notification;
once you change to our custom component for notifications remember to delete this dependency

2023-11-15 12:02 UTC, cmachado92 commented on src/main/java/com/abax/starter/ui/util/UIUtils.java
> +		return dateFormat.get().format((TemporalAccessor) date);
Honestly I have no idea what the TemporalAccessor is and how it works but any function to manipulate data only should be out of UIUtils and actually be in the Utilities class under utilities folder. I realize they are many of these functions from before, so just focus on the one you added, then Ernesto should take care of converting the other ones

2023-11-15 12:02 UTC, cmachado92 requested changes
There are very minor change requests, very good job!

2023-11-15 12:05 UTC, cmachado92 commented on src/main/java/com/abax/starter/ui/view/WorkerForm.java
> +    TextField birthDate = new TextField("Birth Date");
Use DateField for dates

2023-11-15 12:06 UTC, cmachado92 commented on src/main/java/com/abax/starter/ui/view/WorkerForm.java
> +    TextField startDate = new TextField("Start Date");
Use DateField for dates ... DatePicker datePicker = new DatePicker("Start date");

2023-11-15 12:06 UTC, cmachado92 commented on src/main/java/com/abax/starter/ui/view/WorkerForm.java
> +    TextField birthDate = new TextField("Birth Date");
DatePicker datePicker = new DatePicker("Start date");

2023-11-15 12:09 UTC, cmachado92 requested changes
dateFields for dates

2023-11-15 12:10 UTC, cmachado92 commented on src/main/java/com/abax/starter/ui/view/WorkerForm.java
> +//    private final CustomerService customerService;
remove unused Services

2023-11-15 23:48 UTC, greycasas commented
Ready for review.

2023-11-16 00:57 UTC, cmachado92 approved these changes
approved

2023-11-16 01:02 UTC, merged